#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from a4.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "a4.y"

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "list.h"
#define YYDEBUG 1

extern FILE * yyin;
extern FILE* yyout;
void yyerror(const char *str);
bool importFlag;
char* comparisonOp;
char* type;
char* getType(char*);
int caretCounter;
void translateAllocation(char* type);
void printStar(int number);
bool fscanfOn;
bool firstParam;
char* objectVars;
void printTC(char* type, int counter);

#line 25 "a4.y"
typedef union{
	char* str;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDENTIFIER	258
#define	STDIMPORT	259
#define	LOCIMPORT	260
#define	DEFINE	261
#define	MACRO	262
#define	LT	263
#define	GT	264
#define	LIBRARY	265
#define	MACROASSIGNMENT	266
#define	LSQBRACKET	267
#define	RSQBRACKET	268
#define	LCBRACKET	269
#define	RCBRACKET	270
#define	QUESTION	271
#define	CARET	272
#define	INTEGER	273
#define	MOD	274
#define	ASSIGNMENT	275
#define	COMMA	276
#define	FOR	277
#define	WHILE	278
#define	ELSE	279
#define	IF	280
#define	VOID	281
#define	RETURN	282
#define	FALSE	283
#define	TRUE	284
#define	AND	285
#define	POINTER	286
#define	EQUAL	287
#define	NOTEQUAL	288
#define	NOT	289
#define	NULLVAL	290
#define	DOLLAR	291
#define	ALLOCATE	292
#define	INCREMENT	293
#define	DECREMENT	294
#define	DOT	295
#define	BREAK	296
#define	CONTINUE	297
#define	LPARA	298
#define	RPARA	299
#define	ADD	300
#define	SUB	301
#define	DIV	302
#define	MUL	303
#define	TYPE	304
#define	PRINT	305
#define	QUOTEDID	306
#define	IN	307


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDENTIFIER;
static const int STDIMPORT;
static const int LOCIMPORT;
static const int DEFINE;
static const int MACRO;
static const int LT;
static const int GT;
static const int LIBRARY;
static const int MACROASSIGNMENT;
static const int LSQBRACKET;
static const int RSQBRACKET;
static const int LCBRACKET;
static const int RCBRACKET;
static const int QUESTION;
static const int CARET;
static const int INTEGER;
static const int MOD;
static const int ASSIGNMENT;
static const int COMMA;
static const int FOR;
static const int WHILE;
static const int ELSE;
static const int IF;
static const int VOID;
static const int RETURN;
static const int FALSE;
static const int TRUE;
static const int AND;
static const int POINTER;
static const int EQUAL;
static const int NOTEQUAL;
static const int NOT;
static const int NULLVAL;
static const int DOLLAR;
static const int ALLOCATE;
static const int INCREMENT;
static const int DECREMENT;
static const int DOT;
static const int BREAK;
static const int CONTINUE;
static const int LPARA;
static const int RPARA;
static const int ADD;
static const int SUB;
static const int DIV;
static const int MUL;
static const int TYPE;
static const int PRINT;
static const int QUOTEDID;
static const int IN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDENTIFIER=258
	,STDIMPORT=259
	,LOCIMPORT=260
	,DEFINE=261
	,MACRO=262
	,LT=263
	,GT=264
	,LIBRARY=265
	,MACROASSIGNMENT=266
	,LSQBRACKET=267
	,RSQBRACKET=268
	,LCBRACKET=269
	,RCBRACKET=270
	,QUESTION=271
	,CARET=272
	,INTEGER=273
	,MOD=274
	,ASSIGNMENT=275
	,COMMA=276
	,FOR=277
	,WHILE=278
	,ELSE=279
	,IF=280
	,VOID=281
	,RETURN=282
	,FALSE=283
	,TRUE=284
	,AND=285
	,POINTER=286
	,EQUAL=287
	,NOTEQUAL=288
	,NOT=289
	,NULLVAL=290
	,DOLLAR=291
	,ALLOCATE=292
	,INCREMENT=293
	,DECREMENT=294
	,DOT=295
	,BREAK=296
	,CONTINUE=297
	,LPARA=298
	,RPARA=299
	,ADD=300
	,SUB=301
	,DIV=302
	,MUL=303
	,TYPE=304
	,PRINT=305
	,QUOTEDID=306
	,IN=307


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IDENTIFIER=258;
const int YY_parse_CLASS::STDIMPORT=259;
const int YY_parse_CLASS::LOCIMPORT=260;
const int YY_parse_CLASS::DEFINE=261;
const int YY_parse_CLASS::MACRO=262;
const int YY_parse_CLASS::LT=263;
const int YY_parse_CLASS::GT=264;
const int YY_parse_CLASS::LIBRARY=265;
const int YY_parse_CLASS::MACROASSIGNMENT=266;
const int YY_parse_CLASS::LSQBRACKET=267;
const int YY_parse_CLASS::RSQBRACKET=268;
const int YY_parse_CLASS::LCBRACKET=269;
const int YY_parse_CLASS::RCBRACKET=270;
const int YY_parse_CLASS::QUESTION=271;
const int YY_parse_CLASS::CARET=272;
const int YY_parse_CLASS::INTEGER=273;
const int YY_parse_CLASS::MOD=274;
const int YY_parse_CLASS::ASSIGNMENT=275;
const int YY_parse_CLASS::COMMA=276;
const int YY_parse_CLASS::FOR=277;
const int YY_parse_CLASS::WHILE=278;
const int YY_parse_CLASS::ELSE=279;
const int YY_parse_CLASS::IF=280;
const int YY_parse_CLASS::VOID=281;
const int YY_parse_CLASS::RETURN=282;
const int YY_parse_CLASS::FALSE=283;
const int YY_parse_CLASS::TRUE=284;
const int YY_parse_CLASS::AND=285;
const int YY_parse_CLASS::POINTER=286;
const int YY_parse_CLASS::EQUAL=287;
const int YY_parse_CLASS::NOTEQUAL=288;
const int YY_parse_CLASS::NOT=289;
const int YY_parse_CLASS::NULLVAL=290;
const int YY_parse_CLASS::DOLLAR=291;
const int YY_parse_CLASS::ALLOCATE=292;
const int YY_parse_CLASS::INCREMENT=293;
const int YY_parse_CLASS::DECREMENT=294;
const int YY_parse_CLASS::DOT=295;
const int YY_parse_CLASS::BREAK=296;
const int YY_parse_CLASS::CONTINUE=297;
const int YY_parse_CLASS::LPARA=298;
const int YY_parse_CLASS::RPARA=299;
const int YY_parse_CLASS::ADD=300;
const int YY_parse_CLASS::SUB=301;
const int YY_parse_CLASS::DIV=302;
const int YY_parse_CLASS::MUL=303;
const int YY_parse_CLASS::TYPE=304;
const int YY_parse_CLASS::PRINT=305;
const int YY_parse_CLASS::QUOTEDID=306;
const int YY_parse_CLASS::IN=307;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		271
#define	YYFLAG		-32768
#define	YYNTBASE	53

#define YYTRANSLATE(x) ((unsigned)(x) <= 307 ? yytranslate[x] : 144)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     7,    10,    11,    12,    19,    20,    27,
    28,    29,    34,    35,    40,    41,    42,    43,    54,    55,
    56,    57,    58,    74,    75,    76,    77,    84,    85,    88,
    91,    94,    97,   100,   103,   106,   109,   113,   116,   119,
   120,   121,   125,   126,   127,   131,   132,   133,   140,   141,
   142,   146,   147,   148,   154,   155,   156,   157,   169,   170,
   171,   176,   177,   178,   179,   180,   181,   182,   203,   204,
   206,   208,   210,   212,   214,   216,   217,   218,   219,   220,
   229,   230,   231,   232,   240,   242,   244,   246,   248,   250,
   252,   254,   255,   256,   257,   268,   269,   270,   274,   275,
   281,   282,   286,   287,   288,   289,   298,   299,   300,   301,
   310,   311,   312,   317,   319,   321,   325,   329,   330,   331,
   337,   338,   344,   345,   351,   352,   353,   360,   364,   368,
   369,   370,   378,   380,   383,   385,   387,   389,   391,   392,
   393,   398,   399,   404,   405,   410,   411,   416,   417,   422,
   424,   425,   429,   430,   431,   435
};

static const short yyrhs[] = {    54,
    61,     0,     0,    55,    54,     0,    60,    54,     0,     0,
     0,     5,     8,    10,    56,    58,     9,     0,     0,     4,
     8,    10,    58,    57,     9,     0,     0,     0,    21,    10,
    59,    58,     0,     0,     7,     3,    11,    18,     0,     0,
     0,     0,   139,     3,    12,    13,    19,    62,    71,    19,
    63,    61,     0,     0,     0,     0,     0,   139,     3,    12,
    64,   139,     3,    65,    68,    13,    66,    19,    71,    19,
    67,    61,     0,     0,     0,     0,    21,    69,   139,     3,
    70,    68,     0,     0,    76,    71,     0,    82,    71,     0,
    88,    71,     0,   113,    71,     0,   120,    71,     0,   103,
    71,     0,   106,    71,     0,   137,    71,     0,   109,   143,
    71,     0,    72,    71,     0,    74,    71,     0,     0,     0,
    41,    73,   143,     0,     0,     0,    42,    75,   143,     0,
     0,     0,   139,     3,    77,    78,    80,   143,     0,     0,
     0,    20,    79,   131,     0,     0,     0,    21,     3,    81,
    78,    80,     0,     0,     0,     0,    23,    14,    83,    95,
    86,    15,    84,    36,    71,    85,    36,     0,     0,     0,
    94,    87,    95,    86,     0,     0,     0,     0,     0,     0,
     0,    22,    14,     3,    89,    94,    43,   102,    21,    90,
   102,    21,    91,   102,    44,    15,    36,    92,    71,    93,
    36,     0,     0,     8,     0,     9,     0,    32,     0,    33,
     0,    34,     0,    30,     0,     0,     0,     0,     0,    43,
    96,   131,    94,    97,   131,    98,    44,     0,     0,     0,
     0,    43,    99,    94,   100,   131,   101,    44,     0,    18,
     0,     3,     0,   124,     0,   127,     0,    38,     0,    39,
     0,   119,     0,     0,     0,     0,    25,    14,   104,    95,
    86,    15,   105,    36,    71,    36,     0,     0,     0,    24,
   107,   103,     0,     0,    24,    36,   108,    71,    36,     0,
     0,     3,    12,    13,     0,     0,     0,     0,     3,    12,
   110,   118,   111,   116,   112,    13,     0,     0,     0,     0,
    50,    12,    51,   114,   116,    13,   115,   143,     0,     0,
     0,    21,   117,   118,   116,     0,   131,     0,    51,     0,
   124,    40,     3,     0,     3,    40,     3,     0,     0,     0,
     3,    20,   121,   131,   143,     0,     0,   124,    20,   122,
   131,   143,     0,     0,   119,    20,   123,   131,   143,     0,
     0,     0,     3,     8,   125,   102,   126,     9,     0,     3,
    31,     3,     0,   124,    31,     3,     0,     0,     0,    37,
   139,   129,     8,   102,   130,     9,     0,   128,     0,   102,
   132,     0,   109,     0,    35,     0,    29,     0,    28,     0,
     0,     0,    45,   133,   102,   132,     0,     0,    46,   134,
   102,   132,     0,     0,    48,   135,   102,   132,     0,     0,
    47,   136,   102,   132,     0,     0,    27,   138,   131,   143,
     0,    49,     0,     0,    49,   140,   141,     0,     0,     0,
    17,   142,   141,     0,    16,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    39,    42,    42,    43,    46,    46,    46,    47,    48,    50,
    50,    56,    58,    58,    61,    62,    63,    65,    65,    66,
    67,    67,    68,    70,    70,    70,    71,    73,    74,    75,
    76,    77,    78,    79,    80,    81,    82,    83,    84,    87,
    87,    88,    90,    90,    91,    93,    93,    94,    97,    97,
    98,   100,   100,   100,   103,   103,   104,   105,   107,   108,
   108,   109,   112,   112,   118,   123,   124,   125,   127,   127,
   128,   129,   130,   131,   132,   135,   135,   135,   136,   137,
   137,   137,   137,   138,   140,   141,   146,   147,   148,   149,
   150,   153,   153,   153,   154,   157,   157,   158,   158,   158,
   161,   162,   163,   165,   166,   167,   169,   169,   169,   170,
   172,   172,   172,   175,   176,   179,   180,   183,   183,   183,
   184,   184,   185,   185,   188,   188,   189,   191,   192,   195,
   195,   196,   198,   198,   198,   199,   199,   199,   202,   202,
   202,   203,   203,   204,   204,   205,   205,   208,   208,   211,
   212,   213,   215,   215,   216,   218
};

static const char * const yytname[] = {   "$","error","$illegal.","IDENTIFIER",
"STDIMPORT","LOCIMPORT","DEFINE","MACRO","LT","GT","LIBRARY","MACROASSIGNMENT",
"LSQBRACKET","RSQBRACKET","LCBRACKET","RCBRACKET","QUESTION","CARET","INTEGER",
"MOD","ASSIGNMENT","COMMA","FOR","WHILE","ELSE","IF","VOID","RETURN","FALSE",
"TRUE","AND","POINTER","EQUAL","NOTEQUAL","NOT","NULLVAL","DOLLAR","ALLOCATE",
"INCREMENT","DECREMENT","DOT","BREAK","CONTINUE","LPARA","RPARA","ADD","SUB",
"DIV","MUL","TYPE","PRINT","QUOTEDID","IN","Goal","ImportMacroStatements","ImportStatement",
"@1","@2","Libraries","@3","MacroDefinition","FunctionsDefinition","@4","@5",
"@6","@7","@8","@9","Parameters","@10","@11","Statements","BreakStatement","@12",
"ContinueStatement","@13","VarDeclaration","@14","VarDecTimeAssignment","@15",
"VarList","@16","WhileStatement","@17","@18","@19","LoopConditionals","@20",
"ForStatement","@21","@22","@23","@24","@25","ComparisonOperators","ConditionalExpression",
"@26","@27","@28","@29","@30","@31","PrimaryExpr","IfStatement","@32","@33",
"ElseStatement","@34","@35","FunctionCall","@36","@37","@38","PrintStatement",
"@39","@40","Params","@41","PassParameter","DottedVar","AssignmentStatement",
"@42","@43","@44","ArrayLookUp","@45","@46","PointedToValue","AllocationExpresion",
"@47","@48","Expression","ArithmaticExpression","@49","@50","@51","@52","ReturnStatement",
"@53","Type","@54","Caret","@55","Question",""
};
#endif

static const short yyr1[] = {     0,
    53,    54,    54,    54,    55,    56,    55,    57,    55,    58,
    59,    58,    60,    60,    61,    62,    63,    61,    64,    65,
    66,    67,    61,    68,    69,    70,    68,    71,    71,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    72,
    73,    72,    74,    75,    74,    76,    77,    76,    78,    79,
    78,    80,    81,    80,    83,    84,    85,    82,    86,    87,
    86,    86,    89,    90,    91,    92,    93,    88,    94,    94,
    94,    94,    94,    94,    94,    95,    96,    97,    98,    95,
    99,   100,   101,    95,   102,   102,   102,   102,   102,   102,
   102,   103,   104,   105,   103,   106,   107,   106,   108,   106,
   109,   109,   110,   111,   112,   109,   113,   114,   115,   113,
   116,   117,   116,   118,   118,   119,   119,   120,   121,   120,
   122,   120,   123,   120,   125,   126,   124,   127,   127,   129,
   130,   128,   131,   131,   131,   131,   131,   131,   132,   133,
   132,   134,   132,   135,   132,   136,   132,   138,   137,   139,
   140,   139,   141,   142,   141,   143
};

static const short yyr2[] = {     0,
     2,     0,     2,     2,     0,     0,     6,     0,     6,     0,
     0,     4,     0,     4,     0,     0,     0,    10,     0,     0,
     0,     0,    15,     0,     0,     0,     6,     0,     2,     2,
     2,     2,     2,     2,     2,     2,     3,     2,     2,     0,
     0,     3,     0,     0,     3,     0,     0,     6,     0,     0,
     3,     0,     0,     5,     0,     0,     0,    11,     0,     0,
     4,     0,     0,     0,     0,     0,     0,    20,     0,     1,
     1,     1,     1,     1,     1,     0,     0,     0,     0,     8,
     0,     0,     0,     7,     1,     1,     1,     1,     1,     1,
     1,     0,     0,     0,    10,     0,     0,     3,     0,     5,
     0,     3,     0,     0,     0,     8,     0,     0,     0,     8,
     0,     0,     4,     1,     1,     3,     3,     0,     0,     5,
     0,     5,     0,     5,     0,     0,     6,     3,     3,     0,
     0,     7,     1,     2,     1,     1,     1,     1,     0,     0,
     4,     0,     4,     0,     4,     0,     4,     0,     4,     1,
     0,     3,     0,     0,     3,     1
};

static const short yydefact[] = {     2,
     0,     0,     0,    15,     2,     2,     0,     0,     0,   150,
     1,     0,     3,     4,    10,     6,     0,   153,     0,     0,
     8,    10,    14,   154,   152,    19,    11,     0,     0,   153,
     0,     0,    10,     9,     7,   155,    16,     0,    12,    28,
    20,     0,     0,     0,    97,     0,   148,    41,    44,     0,
     0,    28,    28,    28,    28,    28,    28,    28,     0,    28,
     0,    28,     0,    28,     0,    24,   125,   103,   119,     0,
     0,    55,    99,    92,    93,   101,     0,     0,     0,    17,
    38,    39,    29,    30,    31,    34,    35,   156,    28,    32,
   123,    33,   121,     0,    36,    47,    25,     0,     0,   102,
   101,   101,   117,    63,    76,    28,    98,    76,    86,    85,
   138,   137,   136,     0,    89,    90,   139,   135,    91,    87,
    88,   133,     0,    42,    45,   108,    15,    37,   101,   101,
   116,    49,     0,    21,    86,   126,   115,   104,   114,     0,
    69,    77,    59,     0,    59,     0,   130,   140,   142,   146,
   144,   134,     0,   149,   111,    18,     0,     0,    50,    52,
     0,     0,     0,   111,   120,    70,    71,    75,    72,    73,
    74,     0,   101,    69,     0,    60,   100,     0,   128,     0,
     0,     0,     0,     0,   129,   112,     0,   124,   122,   101,
     0,     0,    26,    28,   127,   105,     0,    69,    82,    56,
    76,    94,     0,   139,   139,   139,   139,   101,   109,    51,
    53,    48,    24,     0,     0,     0,    78,   101,     0,    59,
     0,   131,   141,   143,   147,   145,   111,     0,    49,    27,
    22,   106,    64,   101,    83,    28,    61,    28,     0,   113,
   110,    52,    15,     0,    79,     0,    57,     0,   132,    54,
    23,     0,     0,    84,     0,    95,    65,    80,    58,     0,
     0,     0,     0,    66,    28,    67,     0,    68,     0,     0,
     0
};

static const short yydefgoto[] = {   269,
     4,     5,    22,    28,    21,    33,     6,    11,    40,   127,
    32,    66,   162,   243,    98,   133,   213,    51,    52,    77,
    53,    78,    54,   132,   160,   190,   192,   229,    55,   105,
   219,   255,   175,   201,    56,   141,   244,   260,   265,   267,
   176,   143,   173,   234,   253,   174,   218,   246,   117,    57,
   108,   221,    58,    74,   106,    59,   101,   164,   215,    60,
   155,   228,   187,   208,   138,   119,    62,   102,   130,   129,
   120,    99,   163,   121,   122,   180,   239,   139,   152,   181,
   182,   184,   183,    64,    76,    65,    18,    25,    30,    89
};

static const short yypact[] = {    78,
     2,     4,     8,   -25,    78,    78,    21,    29,    32,    48,
-32768,    43,-32768,-32768,    49,-32768,    59,    80,    97,   101,
-32768,    49,-32768,-32768,-32768,   103,-32768,   108,   111,    80,
   102,   -25,    49,-32768,-32768,-32768,-32768,   119,-32768,   159,
-32768,    54,   110,   113,    89,   114,-32768,-32768,-32768,   132,
   126,   159,   159,   159,   159,   159,   159,   159,   130,   159,
   136,   159,   -11,   159,   149,   137,-32768,   144,-32768,   162,
   165,-32768,-32768,   145,-32768,   176,   130,   130,   120,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   159,-32768,
-32768,-32768,-32768,   169,-32768,-32768,-32768,   160,    69,-32768,
   112,   176,-32768,-32768,   133,   159,-32768,   133,    18,-32768,
-32768,-32768,-32768,   -25,-32768,-32768,    55,-32768,-32768,    64,
-32768,-32768,   130,-32768,-32768,-32768,   -25,-32768,   176,   176,
-32768,   157,   -25,-32768,    33,-32768,-32768,-32768,-32768,   130,
   158,-32768,   105,   142,   105,   182,-32768,-32768,-32768,-32768,
-32768,-32768,   186,-32768,   175,-32768,   130,   130,-32768,   177,
   199,   187,   198,   175,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   167,   176,   158,   197,-32768,-32768,   202,-32768,   211,
    69,    69,    69,    69,-32768,-32768,   207,-32768,-32768,   176,
   218,   130,-32768,   159,-32768,-32768,    69,   158,-32768,-32768,
   133,-32768,    69,    55,    55,    55,    55,   112,-32768,-32768,
-32768,-32768,   137,   203,   210,   204,-32768,   176,   188,   105,
   191,-32768,-32768,-32768,-32768,-32768,   175,   130,   157,-32768,
-32768,-32768,-32768,   176,-32768,   159,-32768,   159,   219,-32768,
-32768,   177,   -25,    69,-32768,   185,-32768,   194,-32768,-32768,
-32768,   212,   190,-32768,   196,-32768,-32768,-32768,-32768,    69,
   192,   223,   205,-32768,   159,-32768,   206,-32768,   240,   243,
-32768
};

static const short yypgoto[] = {-32768,
     1,-32768,-32768,-32768,    56,-32768,-32768,  -125,-32768,-32768,
-32768,-32768,-32768,-32768,    31,-32768,-32768,    -1,-32768,-32768,
-32768,-32768,-32768,-32768,    17,-32768,     5,-32768,-32768,-32768,
-32768,-32768,  -141,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
  -114,  -105,-32768,-32768,-32768,-32768,-32768,-32768,   -91,   174,
-32768,-32768,-32768,-32768,-32768,   -54,-32768,-32768,-32768,-32768,
-32768,-32768,  -159,-32768,    41,   -39,-32768,-32768,-32768,-32768,
   -20,-32768,-32768,-32768,-32768,-32768,-32768,   -31,   -73,-32768,
-32768,-32768,-32768,-32768,-32768,    -4,-32768,   220,-32768,     3
};


#define	YYLAST		264


static const short yytable[] = {    12,
    61,   156,   145,   178,   196,    13,    14,   136,    93,     7,
     9,     8,    61,    61,    61,    61,    61,    61,    61,    63,
    61,   118,    61,    10,    61,    67,   172,    38,    94,    68,
    15,    63,    63,    63,    63,    63,    63,    63,    16,    63,
    67,    63,    17,    63,   123,    19,   118,   118,   146,    61,
    81,    82,    83,    84,    85,    86,    87,    70,    90,   199,
    92,    67,    95,   146,  -151,    68,    61,   240,    63,    20,
   140,   135,    70,    69,   118,   118,    23,    29,   237,   124,
   125,     1,     2,   217,     3,    63,   110,   128,    39,   204,
   205,   206,   207,    70,   153,   220,    24,   157,   158,   148,
   149,   150,   151,    94,   144,   216,   115,   116,    26,   147,
    27,   222,   166,   167,   109,    31,    34,   251,   118,    35,
    37,    41,    12,    71,    73,   154,    72,    75,   161,   110,
   223,   224,   225,   226,   168,   118,   169,   170,   171,   111,
   112,   198,   165,    79,    80,    88,   113,   -69,   114,   115,
   116,    96,   252,   118,    61,    91,   100,    97,   210,   188,
   189,    42,   137,   118,   103,   166,   167,   104,   261,    46,
   126,   131,   134,    63,   -40,   142,   159,   177,   109,   118,
    43,    44,    45,    46,   179,    47,   235,   168,   185,   169,
   170,   171,   214,   110,   212,   186,    61,   191,    61,    48,
    49,   193,   245,   111,   112,   194,   195,    10,    50,   197,
   113,   200,   114,   115,   116,    63,   202,    63,   203,   209,
   211,   231,   232,   236,   233,    61,   238,   249,   254,   256,
   241,   259,   257,   258,   247,   262,   248,   263,    12,   270,
   264,   268,   271,   230,    63,   242,   250,   107,   227,    36,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   266
};

static const short yycheck[] = {     4,
    40,   127,   108,   145,   164,     5,     6,    99,    20,     8,
     3,     8,    52,    53,    54,    55,    56,    57,    58,    40,
    60,    76,    62,    49,    64,     8,   141,    32,    40,    12,
    10,    52,    53,    54,    55,    56,    57,    58,    10,    60,
     8,    62,    11,    64,    76,     3,   101,   102,    31,    89,
    52,    53,    54,    55,    56,    57,    58,    40,    60,   174,
    62,     8,    64,    31,    17,    12,   106,   227,    89,    21,
   102,     3,    40,    20,   129,   130,    18,    22,   220,    77,
    78,     4,     5,   198,     7,   106,    18,    89,    33,   181,
   182,   183,   184,    40,    31,   201,    17,   129,   130,    45,
    46,    47,    48,    40,   106,   197,    38,    39,    12,   114,
    10,   203,     8,     9,     3,    13,     9,   243,   173,     9,
    19,     3,   127,    14,    36,   123,    14,    14,   133,    18,
   204,   205,   206,   207,    30,   190,    32,    33,    34,    28,
    29,   173,   140,    12,    19,    16,    35,    43,    37,    38,
    39,     3,   244,   208,   194,    20,    13,    21,   190,   157,
   158,     3,    51,   218,     3,     8,     9,     3,   260,    25,
    51,     3,    13,   194,    16,    43,    20,    36,     3,   234,
    22,    23,    24,    25,     3,    27,   218,    30,     3,    32,
    33,    34,   194,    18,   192,    21,   236,    21,   238,    41,
    42,     3,   234,    28,    29,    19,     9,    49,    50,    43,
    35,    15,    37,    38,    39,   236,    15,   238,     8,    13,
     3,    19,    13,    36,    21,   265,    36,     9,    44,    36,
   228,    36,    21,    44,   236,    44,   238,    15,   243,     0,
    36,    36,     0,   213,   265,   229,   242,    74,   208,    30,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,   265
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 6:
#line 46 "a4.y"
{importFlag=false; printf("#include\"%s\"\n",yyvsp[0].str);;
    break;}
case 7:
#line 46 "a4.y"
{importFlag=true;;
    break;}
case 8:
#line 47 "a4.y"
{printf("#include <%s>\n",yyvsp[-1].str);;
    break;}
case 11:
#line 50 "a4.y"
{
				    if(importFlag)
					    printf("#include <%s>\n",yyvsp[0].str);
				    else 
					printf("#include\"%s\"\n",yyvsp[0].str);
				;
    break;}
case 14:
#line 58 "a4.y"
{printf("#define %s   %s\n",yyvsp[-2].str, yyvsp[0].str);;
    break;}
case 16:
#line 62 "a4.y"
{printTC(type, caretCounter);
				  printf(" %s(){\n",yyvsp[-3].str);;
    break;}
case 17:
#line 63 "a4.y"
{printf("}\n");;
    break;}
case 19:
#line 65 "a4.y"
{printTC(type,caretCounter);printf("%s(",yyvsp[-1].str);;
    break;}
case 20:
#line 66 "a4.y"
{printTC(type, caretCounter);printf(" %s",yyvsp[0].str);;
    break;}
case 21:
#line 67 "a4.y"
{printf("){\n");;
    break;}
case 22:
#line 67 "a4.y"
{printf("}\n");;
    break;}
case 25:
#line 70 "a4.y"
{printf(",");;
    break;}
case 26:
#line 70 "a4.y"
{printTC(type, caretCounter);printf(" %s",yyvsp[0].str);;
    break;}
case 41:
#line 87 "a4.y"
{printf("break");;
    break;}
case 44:
#line 90 "a4.y"
{printf("continue");;
    break;}
case 47:
#line 93 "a4.y"
{printTC(type, caretCounter);printf(" %s",yyvsp[0].str);;
    break;}
case 50:
#line 97 "a4.y"
{printf(" = ");;
    break;}
case 53:
#line 100 "a4.y"
{printf(",%s",yyvsp[0].str);;
    break;}
case 55:
#line 103 "a4.y"
{printf("while(");;
    break;}
case 56:
#line 104 "a4.y"
{printf("){\n");;
    break;}
case 57:
#line 104 "a4.y"
{printf("}\n");;
    break;}
case 60:
#line 108 "a4.y"
{printf(" %s ",comparisonOp);;
    break;}
case 62:
#line 109 "a4.y"
{;
    break;}
case 63:
#line 112 "a4.y"
{printf("for(%s =",yyvsp[0].str);;
    break;}
case 64:
#line 113 "a4.y"
{printf("; ");
				     if(!strcmp(comparisonOp,"!"))
					 printf("%s%s",comparisonOp,yyvsp[-5].str);
				     else printf("%s %s",yyvsp[-5].str, comparisonOp);
				;
    break;}
case 65:
#line 118 "a4.y"
{printf("; ");
					if(!strcmp(comparisonOp,"<"))
					    printf("%s = %s +",yyvsp[-8].str, yyvsp[-8].str);
					else 
					    printf("%s = %s - ",yyvsp[-8].str,yyvsp[-8].str);
				    ;
    break;}
case 66:
#line 124 "a4.y"
{printf("){\n");;
    break;}
case 67:
#line 124 "a4.y"
{printf("}\n");;
    break;}
case 70:
#line 127 "a4.y"
{comparisonOp=yyvsp[0].str;;
    break;}
case 71:
#line 128 "a4.y"
{comparisonOp=yyvsp[0].str;;
    break;}
case 72:
#line 129 "a4.y"
{comparisonOp=yyvsp[0].str;;
    break;}
case 73:
#line 130 "a4.y"
{comparisonOp=yyvsp[0].str;;
    break;}
case 74:
#line 131 "a4.y"
{comparisonOp=yyvsp[0].str;;
    break;}
case 75:
#line 132 "a4.y"
{comparisonOp=yyvsp[0].str;;
    break;}
case 77:
#line 135 "a4.y"
{printf("(");;
    break;}
case 78:
#line 135 "a4.y"
{printf("%s",comparisonOp);;
    break;}
case 79:
#line 136 "a4.y"
{printf(")");;
    break;}
case 81:
#line 137 "a4.y"
{printf("(");;
    break;}
case 82:
#line 137 "a4.y"
{printf("%s",comparisonOp);;
    break;}
case 83:
#line 137 "a4.y"
{printf(")");;
    break;}
case 85:
#line 140 "a4.y"
{printf("%s",yyvsp[0].str);;
    break;}
case 86:
#line 141 "a4.y"
{if(fscanfOn && !firstParam)
						    printf("&%s",yyvsp[0].str);
				   else 
					printf("%s",yyvsp[0].str);
			    ;
    break;}
case 89:
#line 148 "a4.y"
{printf("%s",yyvsp[0].str);;
    break;}
case 90:
#line 149 "a4.y"
{printf("%s",yyvsp[0].str);;
    break;}
case 93:
#line 153 "a4.y"
{printf("if(");;
    break;}
case 94:
#line 153 "a4.y"
{printf("){\n");;
    break;}
case 95:
#line 154 "a4.y"
{printf("}\n");;
    break;}
case 97:
#line 157 "a4.y"
{printf("else ");;
    break;}
case 99:
#line 158 "a4.y"
{printf("else{\n");;
    break;}
case 100:
#line 158 "a4.y"
{printf("}\n");;
    break;}
case 102:
#line 162 "a4.y"
{printf("%s()",yyvsp[-2].str);;
    break;}
case 103:
#line 163 "a4.y"
{printf("%s(",yyvsp[-1].str);if(!strcmp("fscanf",yyvsp[-1].str))
				   fscanfOn=true;firstParam=true;
			    ;
    break;}
case 104:
#line 165 "a4.y"
{firstParam=false;;
    break;}
case 105:
#line 166 "a4.y"
{printf(")"); fscanfOn=false;;
    break;}
case 108:
#line 169 "a4.y"
{printf("printf(%s",yyvsp[0].str);;
    break;}
case 109:
#line 169 "a4.y"
{printf(")");;
    break;}
case 112:
#line 172 "a4.y"
{printf(",");;
    break;}
case 115:
#line 176 "a4.y"
{printf("%s",yyvsp[0].str);;
    break;}
case 116:
#line 179 "a4.y"
{printf(".%s",yyvsp[0].str);;
    break;}
case 117:
#line 180 "a4.y"
{printf("%s.%s",yyvsp[-2].str,yyvsp[0].str);;
    break;}
case 119:
#line 183 "a4.y"
{printf("%s = ",yyvsp[-1].str);;
    break;}
case 121:
#line 184 "a4.y"
{printf(" = ");;
    break;}
case 123:
#line 185 "a4.y"
{printf(" = ");;
    break;}
case 125:
#line 188 "a4.y"
{printf("%s[",yyvsp[-1].str);;
    break;}
case 126:
#line 188 "a4.y"
{printf("]");;
    break;}
case 128:
#line 191 "a4.y"
{printf("%s ->%s",yyvsp[-2].str,yyvsp[0].str);;
    break;}
case 129:
#line 192 "a4.y"
{printf(" ->%s",yyvsp[0].str);;
    break;}
case 130:
#line 195 "a4.y"
{translateAllocation(type);;
    break;}
case 131:
#line 195 "a4.y"
{printf(")");;
    break;}
case 136:
#line 199 "a4.y"
{printf("NULL");;
    break;}
case 137:
#line 199 "a4.y"
{printf("true");;
    break;}
case 138:
#line 199 "a4.y"
{printf("false");;
    break;}
case 140:
#line 202 "a4.y"
{printf("+");;
    break;}
case 142:
#line 203 "a4.y"
{printf("-");;
    break;}
case 144:
#line 204 "a4.y"
{printf("*");;
    break;}
case 146:
#line 205 "a4.y"
{printf("/");;
    break;}
case 148:
#line 208 "a4.y"
{printf("%s ",yyvsp[0].str);;
    break;}
case 150:
#line 211 "a4.y"
{caretCounter=0; type=getType(yyvsp[0].str);;
    break;}
case 151:
#line 212 "a4.y"
{caretCounter=0; type=getType(yyvsp[0].str);;
    break;}
case 154:
#line 215 "a4.y"
{caretCounter++;;
    break;}
case 156:
#line 218 "a4.y"
{printf(";\n");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 220 "a4.y"


int yywrap(){
        return 1;
}

void yyerror(const char *str){
        fprintf(yyout,"ERROR");
        exit(0);
}

main(int argc, char* argv[]){
	importFlag=true;
	comparisonOp= NULL;
	type=NULL;
	caretCounter=0;
	fscanfOn=false;
	firstParam=false;
	objectVars=NULL;
	if(argc > 1){
	   yyin =fopen(argv[1],"r");
	}
	else yyin = stdin;

	if(argc > 2){
		yyout= fopen(argv[2],"w");
	}else
		yyout= stdout;
	if(yyin!=NULL)
	    yyparse();
	else
	    yyerror("ERROR\n");
	
 }

 
 char* getType(char *type){
     char* retType=NULL;
     if(!strcmp(type,"Integer"))
	 retType= "int";
     else if(!strcmp(type,"Character"))
	 retType="char";
     else if(!strcmp(type,"Stack") || !strcmp(type,"Node") || !strcmp(type,"Queue"))
	 retType= "list*";
     else if(!strcmp(type,"pQueue")) 
	 retType="pQueue";
     else if(!strcmp(type,"NodeList"))
	 retType="list**";
     else if(!strcmp(type,"Boolean"))
	 retType="bool";
     else if(!strcmp(type,"Void"))
	 retType="void";
     else if(!strcmp(type,"FileReader"))
	 retType="FILE*";
     return retType;
}

void translateAllocation(char* type){
    if(!strcmp(type,"int"))
	printf("(int*)malloc(sizeof(int)*");
    else if(!strcmp(type,"list**"))
	printf("(list**)malloc(sizeof(list*)*");
    else if(!strcmp(type,"list*"))
	printf("(list*)malloc(sizeof(list)*");
    else if(!strcmp(type,"char"))
	printf("(char*)malloc(sizeof(char)*");
    else if(!strcmp(type,"pQueue"))
	printf("(pQueue*)malloc(sizeof(pQueue)*");
}

void printStar(int number){
    int i=0;
    while(i<number){
	printf("*");
	i++;
    }
}

void printTC(char* type, int counter){
    printf("%s ",type);
    printStar(counter);
}