#!/usr/bin/env python
import os
codepath= "/home/abhisheky/Documents/7thSem/CSD/LAB/Assignment2/"
pinexecPath= "/home/abhisheky/Packages/PinTool/pin"
pinToolPath= "/home/abhisheky/Packages/PinTool/source/tools/ManualExamples/obj-ia32/pinatrace.so"
blockMatrixSourcePath= codepath+"BlockMatrixMult.cpp"
normalMatrixSourcePath= codepath+"NormalMatrixMult.cpp"
blockMatrixExecPath= codepath+"BlockMatrixMult"
normalMatrixExecPath= codepath+"NormalMatrixMult"
normalOutPath= codepath+"NormalMatrixMult.out"
blockOutPath=codepath+"BlockMatrixMult.out"
pinCommand= pinexecPath+" -t "+pinToolPath+" -- " 

print("compilation started.....")
os.system("rm "+normalMatrixExecPath+" "+blockMatrixExecPath)
print("removed pre-existing binaries...")
os.system("g++ -o "+normalMatrixExecPath+" "+normalMatrixSourcePath)
print("NormalMatrixMult.cpp compilation finished.....")
os.system("g++ -o "+blockMatrixExecPath+" "+blockMatrixSourcePath)
print("BlockMatrixMult.cpp compilation finished....")

print("NormalMatrixMult instrumentation starts....")
os.system(pinCommand+normalMatrixExecPath+" "+normalOutPath)
print("NormalMatrixMult instrumentation completed....")
print("BlockMatrixMult instrumentation starts....")
os.system(pinCommand+blockMatrixExecPath+" "+blockOutPath)
print("BlockMatrixMult instrumentation completed....")

cacheSize=int(input("enter cacheSize:"))
cacheLineSize= int(input("enter cacheLineSize:"))
associativity= int(input("enter Associativity:"))
os.system("./main -s "+str(cacheSize)+" -a "+str(associativity)+" -l "+str(cacheLineSize))
